apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  type: NodePort
  selector:
    app: payment
  ports:
  - protocol: TCP
    port: 3009
    targetPort: 3009
    nodePort: 30009 # Choose any available port in the range 30000-32767
